// Generated by CoffeeScript 1.6.3
global.main = {
  init: function() {
    return window.addEventListener('keydown', function(e) {
      if (e.which === '51' && e.shiftKey) {
        return this.maybeHashtagify();
      }
    });
  },
  maybeHashtagify: function() {
    return console.log('wut?');
  }
};

global.main.init();
